compile: sem_creat.out sem_rm.out lion.out jackal.out ranger.out
sem_creat.out: sem_creat.c
	cc -w -o sem_creat.out sem_creat.c
sem_rm.out: sem_rm.c
	cc -w -o sem_rm.out sem_rm.c
lion.out: lion.c
	cc -w -o lion.out lion.c
jackal.out: jackal.c
	cc -w -o jackal.out jackal.c	
ranger.out: ranger.c
	cc -w -o ranger.out ranger.c
clean:
	rm *.out
init: 
	./sem_creat.out	
clear:
	./sem_rm.out						 


