complie:server.out client.out commence.out
server.out: server.c
	cc -w -o server.out server.c
client.out: client.c
	cc -w -o client.out client.c
commence.out: commence.c
	cc -w -o commence.out commence.c
clean:
	rm *.out ser.txt
					
